#!/usr/bin/env python3
"""
Package this STM32H7xx_qspi_flash project into a self-contained CMake source
tree under a user-supplied folder name.

Output layout:

    <project>/
        os_sys.c                       (renamed from Core/Src/main.c)
        main_h/                        (Core/Inc/*.h)
        main_c/                        (Core/Src/*.c except main.c)
        startup/                       (Core/Startup/startup_stm32h750vbtx.s)
        hal_driver/                    (Drivers/CMSIS + Drivers/STM32H7xx_HAL_Driver)
        peripherals/                   (complete Peripherals directory)
        linker/                        (STM32H750VBTX_FLASH.ld + STM32H750VBTX_RAM.ld)
        output/                        (empty - filled by the build)
        cmake/arm-none-eabi-gcc.cmake  (toolchain file)
        CMakeLists.txt                 (top-level CMake project)
        build.py                       (one-click cross-platform build -> elf/bin/hex)

Usage:
    python tools/package_cmake.py <PROJECT_NAME> [--src DIR] [--dst DIR] [--force]
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Pretty terminal output
# ---------------------------------------------------------------------------
class C:
    """ANSI escape sequences. `enable_windows_ansi()` makes them work in cmd.exe."""

    RESET = "\x1b[0m"
    BOLD = "\x1b[1m"
    DIM = "\x1b[2m"
    RED = "\x1b[31m"
    GREEN = "\x1b[32m"
    YELLOW = "\x1b[33m"
    BLUE = "\x1b[34m"
    MAGENTA = "\x1b[35m"
    CYAN = "\x1b[36m"
    WHITE = "\x1b[37m"
    BR_GREEN = "\x1b[92m"
    BR_CYAN = "\x1b[96m"

    @staticmethod
    def enable_windows_ansi() -> None:
        if os.name == "nt":
            os.system("")


def banner(title: str, sub: str = "") -> None:
    bar = "=" * 72
    print(f"\n{C.BOLD}{C.CYAN}{bar}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}  {title}{C.RESET}")
    if sub:
        for line in sub.splitlines():
            print(f"{C.DIM}  {line}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}{bar}{C.RESET}\n")


def step(*args: object) -> None:
    msg = str(args[-1])
    print(f"\n{C.BOLD}{C.BLUE}{msg}{C.RESET}")


def ok(msg: str) -> None:
    print(f"  {C.BR_GREEN}[DONE]{C.RESET} {msg}")


def info(msg: str) -> None:
    print(f"  {C.CYAN}..{C.RESET}   {msg}")


def warn(msg: str) -> None:
    print(f"  {C.YELLOW}!!{C.RESET}   {msg}")


def err(msg: str) -> None:
    print(f"  {C.RED}XX{C.RESET}   {msg}", file=sys.stderr)


def table(rows: list[tuple[str, str]]) -> None:
    if not rows:
        return
    w = max(len(k) for k, _ in rows)
    for k, v in rows:
        print(f"  {C.DIM}{k.ljust(w)}{C.RESET}  {v}")


# ---------------------------------------------------------------------------
# Copy helpers
# ---------------------------------------------------------------------------
def copy_tree(src: Path, dst: Path) -> int:
    """Recursively copy src into dst, returning number of files copied."""
    files = 0
    for root, _dirs, fnames in os.walk(src):
        rel = Path(root).relative_to(src)
        out_dir = dst / rel
        out_dir.mkdir(parents=True, exist_ok=True)
        for f in fnames:
            shutil.copy2(Path(root) / f, out_dir / f)
            files += 1
    return files


# ---------------------------------------------------------------------------
# CMake templates (use @PROJECT_NAME@ as the substitution placeholder so no
# Python brace-escaping is needed for CMake's normal ${...} syntax)
# ---------------------------------------------------------------------------
TOOLCHAIN_CMAKE = """\
# Auto-generated by package_cmake.py
# arm-none-eabi-gcc cross-compile toolchain for STM32H750VBTx.

set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
set(CMAKE_OBJCOPY      arm-none-eabi-objcopy CACHE FILEPATH "objcopy")
set(CMAKE_SIZE         arm-none-eabi-size    CACHE FILEPATH "size")

# Cortex-M7 with single-precision FPU, hard-float ABI (matches the .cproject).
set(MCU_FLAGS "-mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb")

set(CMAKE_C_FLAGS_INIT   "${MCU_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${MCU_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${MCU_FLAGS} -x assembler-with-cpp")
set(CMAKE_EXE_LINKER_FLAGS_INIT
    "${MCU_FLAGS} --specs=nano.specs --specs=nosys.specs -Wl,--gc-sections")
"""


CMAKELISTS = """\
# Auto-generated by package_cmake.py
cmake_minimum_required(VERSION 3.20)

set(PROJECT_NAME "@PROJECT_NAME@")
project(${PROJECT_NAME} C ASM)

# ---------------- Linker scripts ----------------
set(LINKER_FLASH ${CMAKE_SOURCE_DIR}/linker/STM32H750VBTX_FLASH.ld)
set(LINKER_RAM   ${CMAKE_SOURCE_DIR}/linker/STM32H750VBTX_RAM.ld)
set(LINKER_SCRIPT ${LINKER_FLASH} CACHE FILEPATH "Linker script (FLASH or RAM)")

# ---------------- Output folder ----------------
set(OUTPUT_DIR ${CMAKE_SOURCE_DIR}/output)
file(MAKE_DIRECTORY ${OUTPUT_DIR})

# ---------------- Compile options ----------------
add_compile_definitions(
    USE_PWR_LDO_SUPPLY
    USE_HAL_DRIVER
    STM32H750xx
)

add_compile_options(
    -Og -g3
    -Wall
    -fdata-sections
    -ffunction-sections
    # Force ANSI diagnostics even when CMake/Ninja runs the compiler without a TTY
    # (e.g. python build.py). GNU and Clang both accept this flag.
    $<$<COMPILE_LANG_AND_ID:C,ARMClang,AppleClang,Clang,GNU>:-fdiagnostics-color=always>
)

# ---------------- Sources ----------------
file(GLOB         ENTRY_SRC   ${CMAKE_SOURCE_DIR}/os_sys.c)
file(GLOB_RECURSE MAIN_C_SRC  ${CMAKE_SOURCE_DIR}/main_c/*.c)
file(GLOB_RECURSE HAL_SRC     ${CMAKE_SOURCE_DIR}/hal_driver/STM32H7xx_HAL_Driver/Src/*.c)
file(GLOB_RECURSE PERIPH_SRC  ${CMAKE_SOURCE_DIR}/peripherals/*.c)
file(GLOB         STARTUP_SRC ${CMAKE_SOURCE_DIR}/startup/*.s)
file(GLOB         PERIPH_INC_DIRS LIST_DIRECTORIES true ${CMAKE_SOURCE_DIR}/peripherals/*/Inc)

add_executable(${PROJECT_NAME}.elf
    ${ENTRY_SRC}
    ${MAIN_C_SRC}
    ${HAL_SRC}
    ${PERIPH_SRC}
    ${STARTUP_SRC}
)

target_include_directories(${PROJECT_NAME}.elf PRIVATE
    ${CMAKE_SOURCE_DIR}/main_h
    ${CMAKE_SOURCE_DIR}/hal_driver/CMSIS/Include
    ${CMAKE_SOURCE_DIR}/hal_driver/CMSIS/Device/ST/STM32H7xx/Include
    ${CMAKE_SOURCE_DIR}/hal_driver/STM32H7xx_HAL_Driver/Inc
    ${CMAKE_SOURCE_DIR}/hal_driver/STM32H7xx_HAL_Driver/Inc/Legacy
    ${PERIPH_INC_DIRS}
)

target_link_options(${PROJECT_NAME}.elf PRIVATE
    -T${LINKER_SCRIPT}
    -Wl,-Map=${CMAKE_BINARY_DIR}/${PROJECT_NAME}.map
)

# ---------------- Post-build: .elf / .hex / .bin into output/ ----------------
add_custom_command(TARGET ${PROJECT_NAME}.elf POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory ${OUTPUT_DIR}
    COMMAND ${CMAKE_OBJCOPY} -O ihex   $<TARGET_FILE:${PROJECT_NAME}.elf> ${OUTPUT_DIR}/${PROJECT_NAME}.hex
    COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${PROJECT_NAME}.elf> ${OUTPUT_DIR}/${PROJECT_NAME}.bin
    COMMAND ${CMAKE_COMMAND} -E copy   $<TARGET_FILE:${PROJECT_NAME}.elf> ${OUTPUT_DIR}/${PROJECT_NAME}.elf
    # Ninja leaves the last progress line without a trailing newline; echo keeps
    # arm-none-eabi-size output from appearing on the same line as [n/n] Linking...
    COMMAND ${CMAKE_COMMAND} -E echo ""
    COMMAND ${CMAKE_SIZE}              $<TARGET_FILE:${PROJECT_NAME}.elf>
    COMMENT "Generating ${PROJECT_NAME}.elf / .hex / .bin in output/"
)
"""


BUILD_PY = '''\
#!/usr/bin/env python3
"""
One-click cross-platform build for the CMake source package.

Runs:
    cmake -S . -B build -G <generator> \\
        -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi-gcc.cmake \\
        -DCMAKE_BUILD_TYPE=<type>
    cmake --build build

Artefacts (.elf / .hex / .bin) are produced in ./output/ by the post-build step
defined in CMakeLists.txt.

Auto-generated by package_cmake.py.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


class C:
    RESET    = "\\x1b[0m"
    BOLD     = "\\x1b[1m"
    DIM      = "\\x1b[2m"
    RED      = "\\x1b[31m"
    YELLOW   = "\\x1b[33m"
    BLUE     = "\\x1b[34m"
    CYAN     = "\\x1b[36m"
    BR_GREEN = "\\x1b[92m"

    @staticmethod
    def enable_windows_ansi() -> None:
        if os.name == "nt":
            os.system("")


def banner(title: str, sub: str = "") -> None:
    bar = "=" * 72
    print(f"\\n{C.BOLD}{C.CYAN}{bar}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}  {title}{C.RESET}")
    if sub:
        for line in sub.splitlines():
            print(f"{C.DIM}  {line}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}{bar}{C.RESET}\\n")


def step(*args: object) -> None:
    msg = str(args[-1])
    print(f"\\n{C.BOLD}{C.BLUE}{msg}{C.RESET}")


def ok(msg: str) -> None:
    print(f"  {C.BR_GREEN}[DONE]{C.RESET} {msg}")


def warn(msg: str) -> None:
    print(f"  {C.YELLOW}!!{C.RESET}   {msg}")


def err(msg: str) -> None:
    print(f"  {C.RED}XX{C.RESET}   {msg}", file=sys.stderr)


def run(cmd: list, cwd: Path | None = None) -> None:
    pretty = " ".join(str(c) for c in cmd)
    print(f"  {C.DIM}$ {pretty}{C.RESET}")
    env = os.environ.copy()
    # Many tools disable color when stdout is not a TTY (common under `python build.py`).
    env.setdefault("FORCE_COLOR", "1")
    env.setdefault("CLICOLOR_FORCE", "1")
    # CMake 3.24+: colored configure messages when supported.
    env.setdefault("CMAKE_COLOR_DIAGNOSTICS", "ON")
    # GCC uses GCC_COLORS together with -fdiagnostics-color=always (see CMakeLists.txt).
    if "GCC_COLORS" not in env:
        env["GCC_COLORS"] = "error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01"
    completed = subprocess.run(cmd, cwd=str(cwd) if cwd else None, env=env)
    if completed.returncode != 0:
        err(f"Command failed (exit {completed.returncode}): {pretty}")
        sys.exit(completed.returncode)


def pick_generator(preferred: str | None) -> str:
    if preferred:
        return preferred
    if shutil.which("ninja"):
        return "Ninja"
    if os.name == "nt":
        if shutil.which("mingw32-make"):
            return "MinGW Makefiles"
        if shutil.which("make"):
            return "Unix Makefiles"
        return "MinGW Makefiles"
    return "Unix Makefiles"


def exe(name: str) -> str:
    return f"{name}.exe" if os.name == "nt" else name


def existing_dirs(paths: list[Path]) -> list[Path]:
    seen: set[Path] = set()
    dirs: list[Path] = []
    for p in paths:
        if not p or str(p) == "." or not p.exists():
            continue
        resolved = p.resolve()
        if resolved not in seen:
            seen.add(resolved)
            dirs.append(resolved)
    return dirs


def cubeide_search_roots(root: Path) -> list[Path]:
    env = os.environ
    home = Path(env.get("HOME") or env.get("USERPROFILE") or "")
    candidates: list[Path] = [
        root,
        root.parent,
        # Explicit environment overrides honoured on every OS.
        Path(env.get("STM32CUBEIDE_TOOLCHAIN", "")),
        Path(env.get("STM32CUBEIDE_PATH", "")),
        Path(env.get("STM32CubeIDE", "")),
    ]

    if os.name == "nt":
        candidates += [
            Path(env.get("ProgramFiles", "")) / "STMicroelectronics",
            Path(env.get("ProgramFiles(x86)", "")) / "STMicroelectronics",
            Path(env.get("LOCALAPPDATA", "")) / "Programs" / "STMicroelectronics",
            home / "STMicroelectronics",
            Path("C:/ST"),
            Path("C:/STMicroelectronics"),
        ]
    elif sys.platform == "darwin":
        candidates += [
            Path("/Applications"),
            Path("/Applications/STMicroelectronics"),
            Path("/Library/STMicroelectronics"),
            home / "Applications",
            home / "Applications/STMicroelectronics",
            home / "STMicroelectronics",
            Path("/opt/st"),
            Path("/opt/STMicroelectronics"),
        ]
    else:
        candidates += [
            Path("/opt/st"),
            Path("/opt/STMicroelectronics"),
            Path("/usr/local/STMicroelectronics"),
            home / "STMicroelectronics",
            home / ".local/share/STMicroelectronics",
            home / "Applications/STMicroelectronics",
        ]

    return existing_dirs(candidates)


def discover_arm_gcc(root: Path, explicit_bin: str | None) -> Path | None:
    if explicit_bin:
        toolchain_path = Path(explicit_bin).expanduser().resolve()
        gcc = toolchain_path if toolchain_path.is_file() else toolchain_path / exe("arm-none-eabi-gcc")
        return gcc if gcc.exists() else None

    found = shutil.which("arm-none-eabi-gcc")
    if found:
        return Path(found).resolve()

    gcc_name = exe("arm-none-eabi-gcc")
    patterns = [
        # Windows / generic capitalised CubeIDE folders.
        f"STM32CubeIDE*/plugins/**/tools/bin/{gcc_name}",
        f"STM32CubeIDE*/plugins/**/bin/{gcc_name}",
        f"STM32CubeIDE*/STM32CubeIDE/plugins/**/tools/bin/{gcc_name}",
        f"STM32CubeIDE*/STM32CubeIDE/plugins/**/bin/{gcc_name}",
        # Linux installer folders typically lowercase + versioned.
        f"stm32cubeide*/plugins/**/tools/bin/{gcc_name}",
        f"stm32cubeide*/plugins/**/bin/{gcc_name}",
        # macOS .app bundle layout.
        f"STM32CubeIDE*.app/Contents/Eclipse/plugins/**/tools/bin/{gcc_name}",
        f"STM32CubeIDE*.app/Contents/Eclipse/plugins/**/bin/{gcc_name}",
        # When the search root is already inside an Eclipse install.
        f"plugins/**/tools/bin/{gcc_name}",
        f"plugins/**/bin/{gcc_name}",
        # Catch-all fallback (slow but correct).
        f"**/{gcc_name}",
    ]
    matches: list[Path] = []
    for base in cubeide_search_roots(root):
        for pattern in patterns:
            matches.extend(
                p for p in base.glob(pattern)
                if p.is_file() and p.name.lower() == gcc_name.lower()
            )
    if not matches:
        return None

    # Prefer the newest CubeIDE bundled toolchain when multiple versions exist.
    matches.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return matches[0].resolve()


def add_toolchain_to_path(gcc_path: Path) -> Path:
    bin_dir = gcc_path.parent
    current = os.environ.get("PATH", "")
    os.environ["PATH"] = f"{bin_dir}{os.pathsep}{current}"
    return bin_dir


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="One-click build for the CMake source package.")
    p.add_argument("--build-dir", default="build", help="CMake build directory (default: build)")
    p.add_argument("--build-type", default="Debug",
                   choices=["Debug", "Release", "RelWithDebInfo", "MinSizeRel"],
                   help="CMake build type (default: Debug)")
    p.add_argument("--generator", default=None,
                   help="CMake generator (default: Ninja if available, else Make)")
    p.add_argument("--toolchain-bin", default=None,
                   help="Folder containing arm-none-eabi-gcc. Optional; auto-detected from PATH/CubeIDE.")
    p.add_argument("--clean", action="store_true",
                   help="Remove the build directory before configuring")
    return p.parse_args()


def main() -> int:
    C.enable_windows_ansi()
    args = parse_args()
    root = Path(__file__).resolve().parent
    build_dir = root / args.build_dir
    generator = pick_generator(args.generator)

    banner(
        "Build CMake source package",
        f"root        = {root}\\n"
        f"build-dir   = {build_dir}\\n"
        f"build-type  = {args.build_type}\\n"
        f"generator   = {generator}",
    )

    # 1) Toolchain probe
    step(1, 4, "Probing toolchain")
    cmake_path = shutil.which("cmake")
    gcc_path = discover_arm_gcc(root, args.toolchain_bin)
    if not cmake_path:
        err("cmake not found on PATH")
        return 2
    if not gcc_path:
        gcc_name = exe("arm-none-eabi-gcc")
        err("arm-none-eabi-gcc not found on PATH or in common STM32CubeIDE install folders")
        print(f"  hint: run with --toolchain-bin <folder-that-contains-{gcc_name}>")
        return 2
    toolchain_bin = add_toolchain_to_path(gcc_path)
    ok(f"cmake             {cmake_path}")
    ok(f"toolchain bin     {toolchain_bin}")
    ok(f"arm-none-eabi-gcc {gcc_path}")

    # 2) Prepare build directory
    step(2, 4, "Preparing build directory")
    if args.clean and build_dir.exists():
        warn(f"Removing existing build directory: {build_dir}")
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True, exist_ok=True)
    ok(f"build directory   {build_dir}")

    # 3) Configure
    step(3, 4, "Configuring CMake")
    run([
        "cmake", "-S", str(root), "-B", str(build_dir),
        "-G", generator,
        "-DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi-gcc.cmake",
        f"-DCMAKE_BUILD_TYPE={args.build_type}",
        "-DCMAKE_COLOR_DIAGNOSTICS=ON",
    ])

    # 4) Build
    step(4, 4, "Building")
    run(["cmake", "--build", str(build_dir)])
    # Ninja may leave the cursor on the same line as the last progress update.
    print()
    sys.stdout.flush()

    outp = root / "output"
    print(f"  {C.BR_GREEN}[BUILD_OK]{C.RESET} :- {outp}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        err("Interrupted")
        sys.exit(130)
'''


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
REQUIRED = {
    "Core/Src/main.c":                       "main source",
    "Core/Inc/main.h":                       "main header",
    "Core/Startup/startup_stm32h750vbtx.s":  "startup",
    "Drivers/CMSIS":                         "CMSIS",
    "Drivers/STM32H7xx_HAL_Driver":          "STM32H7xx HAL",
    "Peripherals":                           "peripherals",
    "STM32H750VBTX_FLASH.ld":                "flash linker",
    "STM32H750VBTX_RAM.ld":                  "ram linker",
}


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    default_src = script_dir.parent

    p = argparse.ArgumentParser(
        description="Package the STM32H7 project into a CMake source tree.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python tools/package_cmake.py myapp\n"
            "  python tools/package_cmake.py myapp --dst ./release/myapp --force\n"
        ),
    )
    p.add_argument("project_name", help="Output project / CMake target name.")
    p.add_argument("--src", type=Path, default=default_src,
                   help=f"Source project root (default: {default_src}).")
    p.add_argument("--dst", type=Path, default=None,
                   help="Destination folder (default: <src>/packages/<project_name>).")
    p.add_argument("--force", action="store_true",
                   help="Overwrite the destination if it already exists.")
    return p.parse_args()


def validate_project_name(name: str) -> None:
    if not re.match(r"^[A-Za-z][A-Za-z0-9_.-]*$", name):
        err(f"Invalid project name: {name!r}. "
            f"Must start with a letter and contain only letters, digits, '_', '.', '-'.")
        sys.exit(2)


def verify_source_layout(src: Path) -> None:
    missing: list[str] = []
    for rel, label in REQUIRED.items():
        if (src / rel).exists():
            ok(f"{label:<18}  {rel}")
        else:
            err(f"{label:<18}  {rel}  (NOT FOUND)")
            missing.append(rel)
    if missing:
        err("Aborting: the source project is missing required files (see above).")
        sys.exit(3)


def prepare_destination(dst: Path, force: bool) -> None:
    if dst.exists():
        if not force:
            err(f"Destination already exists: {dst}\n  use --force to overwrite.")
            sys.exit(4)
        warn(f"Removing existing destination: {dst}")
        shutil.rmtree(dst)
    for sub in ("", "main_h", "main_c", "startup",
                "hal_driver", "peripherals", "linker", "output", "cmake"):
        (dst / sub).mkdir(parents=True, exist_ok=True)
    ok(f"Created scaffolding at {dst}")


def copy_sources(src: Path, dst: Path) -> dict[str, int]:
    stats: dict[str, int] = {}

    # os_sys.c (renamed from main.c)
    shutil.copy2(src / "Core/Src/main.c", dst / "os_sys.c")
    stats["os_sys.c"] = 1
    ok("Core/Src/main.c  ->  os_sys.c")

    # main_h: Core/Inc/*
    stats["main_h"] = copy_tree(src / "Core/Inc", dst / "main_h")
    ok(f"Core/Inc/*  ->  main_h/  ({stats['main_h']} files)")

    # main_c: Core/Src/* except main.c
    n = 0
    for p in (src / "Core/Src").iterdir():
        if p.is_file() and p.name != "main.c":
            shutil.copy2(p, dst / "main_c" / p.name)
            n += 1
    stats["main_c"] = n
    ok(f"Core/Src/*  (excluding main.c)  ->  main_c/  ({n} files)")

    # startup
    stats["startup"] = copy_tree(src / "Core/Startup", dst / "startup")
    ok(f"Core/Startup/*  ->  startup/  ({stats['startup']} files)")

    # hal_driver: Drivers/CMSIS + Drivers/STM32H7xx_HAL_Driver
    for d in ("CMSIS", "STM32H7xx_HAL_Driver"):
        n = copy_tree(src / f"Drivers/{d}", dst / "hal_driver" / d)
        stats[f"hal_driver/{d}"] = n
        ok(f"Drivers/{d}  ->  hal_driver/{d}/  ({n} files)")

    # peripherals: copy the complete Peripherals tree so future drivers are included.
    stats["peripherals"] = copy_tree(src / "Peripherals", dst / "peripherals")
    ok(f"Peripherals/*  ->  peripherals/  ({stats['peripherals']} files)")

    # linker scripts
    n = 0
    for ld in ("STM32H750VBTX_FLASH.ld", "STM32H750VBTX_RAM.ld"):
        shutil.copy2(src / ld, dst / "linker" / ld)
        n += 1
    stats["linker"] = n
    ok(f"*.ld  ->  linker/  ({n} files)")

    return stats


def write_cmake_files(dst: Path, project_name: str) -> None:
    (dst / "cmake" / "arm-none-eabi-gcc.cmake").write_text(TOOLCHAIN_CMAKE, encoding="utf-8")
    ok("cmake/arm-none-eabi-gcc.cmake")

    rendered = CMAKELISTS.replace("@PROJECT_NAME@", project_name)
    (dst / "CMakeLists.txt").write_text(rendered, encoding="utf-8")
    ok("CMakeLists.txt")


def write_build_scripts(dst: Path) -> None:
    # Emit a single cross-platform Python build entry point. Use open() with explicit
    # newline= for Python 3.9 compatibility.
    build_py = dst / "build.py"
    with build_py.open("w", encoding="utf-8", newline="\n") as f:
        f.write(BUILD_PY)
    try:
        build_py.chmod(0o755)
    except OSError:
        pass
    ok("build.py (cross-platform)")


def main() -> int:
    C.enable_windows_ansi()
    args = parse_args()

    validate_project_name(args.project_name)
    src = args.src.resolve()
    dst = (args.dst if args.dst else src / "packages" / args.project_name).resolve()

    banner(
        f"Packaging STM32H7 source for {args.project_name}",
        f"source       = {src}\n"
        f"destination  = {dst}\n"
        f"force        = {args.force}",
    )

    step(1, 6, "Verifying source project layout")
    verify_source_layout(src)

    step(2, 6, "Preparing destination scaffolding")
    prepare_destination(dst, args.force)

    step(3, 6, "Copying project sources")
    stats = copy_sources(src, dst)

    step(4, 6, "Emitting CMake template files")
    write_cmake_files(dst, args.project_name)

    step(5, 6, "Emitting one-click build script")
    write_build_scripts(dst)

    banner(
        "Success",
        f"open  : {dst}\n"
        f"build : python build.py   (cross-platform; --clean, --build-type, --generator supported)\n"
        f"output: {dst / 'output'}  (will contain .elf / .hex / .bin)",
    )

    print(f"{C.BOLD}{C.CYAN}Summary{C.RESET}")
    table([
        ("project",       args.project_name),
        ("destination",   str(dst)),
        ("os_sys.c",      f"{stats['os_sys.c']} file"),
        ("main_h/",       f"{stats['main_h']} files"),
        ("main_c/",       f"{stats['main_c']} files"),
        ("startup/",      f"{stats['startup']} files"),
        ("hal_driver/",   f"{stats['hal_driver/CMSIS'] + stats['hal_driver/STM32H7xx_HAL_Driver']} files"),
        ("peripherals/",  f"{stats['peripherals']} files"),
        ("linker/",       f"{stats['linker']} files"),
    ])
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        err("Interrupted")
        sys.exit(130)
